### ISSUE TITLE
SyntaxError: JSON5: invalid character 'u' at 1:1

### ISSUE THREAD

**Issue by rodrigobdz** [huggingface/chat-ui#1225]
Where can I find out more about the following error? Is there an issue with the existing template?

## Reproduction Steps

1. Deploy [Chat UI using default template](https://huggingface.co/new-space?template=huggingchat/chat-ui-template) with `MONGO_URL` set to `mongodb+srv://<USER_SECRET>:<PASSWORD_SECRET>@<CLUSTER_SECRET>`
2. Add secret called `HF_TOKEN` with access token value.

## Error Logs

Additionally to https://github.com/huggingface/chat-ui/issues/1174, the following error is shown:

```
2024-05-30T11:56:43: PM2 log: [--no-daemon] Exit on target PM2 exit pid=403
11:56:43 2|index  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
11:56:43 2|index  | SyntaxError: JSON5: invalid character 'u' at 1:1
11:56:43 2|index  |     at syntaxError (/app/node_modules/json5/lib/parse.js:1110:17)
11:56:43 2|index  |     at invalidChar (/app/node_modules/json5/lib/parse.js:1055:12)
11:56:43 2|index  |     at Object.value (/app/node_modules/json5/lib/parse.js:309:15)
11:56:43 2|index  |     at lex (/app/node_modules/json5/lib/parse.js:100:42)
11:56:43 2|index  |     at Object.parse (/app/node_modules/json5/lib/parse.js:25:17)
11:56:43 2|index  |     at file:///app/build/server/chunks/auth-9412170c.js:28:16
11:56:43 2|index  |     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
11:56:43 2|index  |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
11:56:43 2|index  |     at async Server.init (file:///app/build/server/index.js:4189:24)
11:56:43 2|index  |     at async file:///app/build/handler.js:1140:1
```

## Tried so far

The error seems similar to https://github.com/huggingface/chat-ui/issues/851#issuecomment-2133654266 and I tried finding out how that past issue was fixed, but got no reply so far.

**Comment by nsarrazin** [comment]
I think the template is broken. Will fix

**Comment by gabriel-tumlos** [comment]
Any update on a fix for this?

**Comment by pronitagrawalvera** [comment]
Hi @nsarrazin Any update on this, We are also facing the same issue with docker

**Comment by ddandrea00** [comment]
We are also facing the same issue @nsarrazin any updates on what is causing this and how to fix it locally in the meantime while you make fixes on your end?

**Comment by marburps** [comment]
Same issue

**Comment by gururise** [comment]
Just ran into this today:
```
2025/01/16 12:20PM 50 Internal Error | pid=22 hostname=fa7cd4c2a7ee} errorId=16c8a084-3349-4704-8da8-3ea13a504061 status=500 stack=SyntaxError: JSON5: invalid character 'm' at 1:1
    at syntaxError (/app/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/app/node_modules/json5/lib/parse.js:1055:12)
    at Object.value (/app/node_modules/json5/lib/parse.js:309:15)
    at lex (/app/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/app/node_modules/json5/lib/parse.js:25:17)
    at file:///app/build/server/chunks/models-7I7wXN6P.js:6357:146
```

**Comment by marburps** [comment]
I've experimented extensively with this and ran into the same errors for hours. I know now that it is all related to invalid info in the .env.local file. It is very picky. Once you got your env.local file right, it'll work.
