### ISSUE TITLE
Fresh local install cannot search for any topic

### ISSUE THREAD

**Issue by iChristGit** [huggingface/chat-ui#1282]
I have updates to latest version and have issue with websearch, tried a fresh install as well
No matter what term I search for this is the result:
![image](https://github.com/huggingface/chat-ui/assets/20077386/8bc7d500-fe05-4d46-8e2b-f458e3686469)

Any Idea? I think it should be easily reproducible on latest version as I was able to search before git pull

**Comment by nsarrazin** [comment]
Could you pull latest and try again ?

**Comment by iChristGit** [comment]
> Could you pull latest and try again ?

I tried that, fresh install and exactly the same issue as originally posted
![image](https://github.com/huggingface/chat-ui/assets/20077386/ac31daa3-1cf7-43a8-a1ed-6e31cb41f055)
Maybe its caused because of me doing the audit fix?

**Comment by neven4** [comment]
Hi @iChristGit, do you have some errors in the console?

**Comment by iChristGit** [comment]
> Hi @iChristGit, do you have some errors in the console?

Yeah I forgot about that, here is the logs:
I do have Google Chrome installed normally in windows11

```
  VITE v4.5.3  ready in 1317 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
[23:45:45.859] INFO (24624): [MIGRATIONS] Begin check...
[23:45:45.877] INFO (24624): [MIGRATIONS] "Update search assistants" already applied. Skipping...
[23:45:45.877] INFO (24624): [MIGRATIONS] "Update deprecated models in assistants with the default model" should not be applied for this run. Skipping...
[23:45:45.877] INFO (24624): [MIGRATIONS] "Add empty 'tools' record in settings" already applied. Skipping...
[23:45:45.877] INFO (24624): [MIGRATIONS] "Convert message updates to the new schema" already applied. Skipping...
[23:45:45.877] INFO (24624): [MIGRATIONS] "Convert message files to the new schema" already applied. Skipping...
[23:45:45.877] INFO (24624): [MIGRATIONS] "Trim message updates to reduce stored size" already applied. Skipping...
[23:45:45.877] INFO (24624): [MIGRATIONS] All migrations applied. Releasing lock
[23:45:45.893] INFO (24624): Metrics server listening on port 5565

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.347: invalid unclassed type '(NULL)' in class cast to '(NULL)'

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.347: invalid unclassed type '(NULL)' in class cast to '(NULL)'

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.348: invalid unclassed type '(NULL)' in class cast to '(NULL)'

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.348: invalid unclassed type '(NULL)' in class cast to '(NULL)'

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.348: invalid unclassed type '(NULL)' in class cast to '(NULL)'

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.348: invalid unclassed type '(NULL)' in class cast to '(NULL)'

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.349: invalid unclassed type '(NULL)' in class cast to '(NULL)'

(process:24624): GLib-GObject-CRITICAL **: 23:45:46.349: invalid unclassed type '(NULL)' in class cast to '(NULL)'
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
No text found in the first 8 results
[23:46:18.896] ERROR (24624): Error scraping webpage: https://en.wikipedia.org/wiki/Michael_Jackson
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
[23:46:18.897] ERROR (24624): Error scraping webpage: https://en.wikipedia.org/wiki/Health_and_appearance_of_Michael_Jackson
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
[23:46:18.897] ERROR (24624): Error scraping webpage: https://en.wikipedia.org/wiki/Death_of_Michael_Jackson
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
[23:46:18.897] ERROR (24624): Error scraping webpage: https://en.wikipedia.org/wiki/Estate_of_Michael_Jackson
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
[23:46:18.897] ERROR (24624): Error scraping webpage: https://en.wikipedia.org/wiki/Michael_(Michael_Jackson_album)
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
[23:46:18.897] ERROR (24624): Error scraping webpage: https://www.michaeljackson.com/
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
[23:46:18.897] ERROR (24624): Error scraping webpage: https://www.michaeljackson.com/au/
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
[23:46:18.897] ERROR (24624): Error scraping webpage: https://www.michaeljackson.com/community/at-michael-jackson-concerts/
    err: {
      "type": "Error",
      "message": "browserType.launch: Executable doesn't exist at C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-1117\\chrome-win\\chrome.exe\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║
             ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝",
      "stack":
          browserType.launch: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\chromium-1117\chrome-win\chrome.exe
          ╔═════════════════════════════════════════════════════════════════════════╗
          ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          ║ Please run the following command to download new browsers:              ║
          ║                                                                         ║
          ║     npx playwright install                                              ║
          ║                                                                         ║
          ║ <3 Playwright Team                                                      ║
          ╚═════════════════════════════════════════════════════════════════════════╝
              at getBrowser (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:22:56)
              at getPlaywrightCtx (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:32:24)
              at Module.withPage (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\playwright.ts:54:21)
              at scrapeUrl (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:35:32)
              at eval (E:\AI-Apps\chat-ui\src\lib\server\websearch\scrape\scrape.ts:21:24)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:9:11)
              at Module.runWebSearch (E:\AI-Apps\chat-ui\src\lib\server\websearch\runWebSearch.ts:35:58)
              at textGenerationWithoutTitle (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:40:52)
              at Module.mergeAsyncGenerators (E:\AI-Apps\chat-ui\src\lib\utils\mergeAsyncGenerators.ts:20:13)
              at async Module.textGeneration (E:\AI-Apps\chat-ui\src\lib\server\textGeneration\index.ts:24:3)
              at async Object.start (E:\AI-Apps\chat-ui\src\routes\conversation\[id]\+server.ts:325:26)
      "name": "Error"
    }
```

**Comment by neven4** [comment]
Oh, I had the same problem. `npx playwright install` fixed issue for me 👍

**Comment by iChristGit** [comment]
> Oh, I had the same problem. `npx playwright install` fixed issue for me 👍

After running the command the initial errors fixed but there are still issues with search.. does it work correctly for you on latest version?

**Comment by neven4** [comment]
> > Oh, I had the same problem. `npx playwright install` fixed issue for me 👍
> 
> After running the command the initial errors fixed but there are still issues with search.. does it work correctly for you on latest version?

Everything seems to be fine for me 👍
