### ISSUE TITLE
Websearch not working

### ISSUE THREAD

**Issue by Ubermm** [huggingface/chat-ui#1288]
I am using the serper.dev api and the default mistral-instruct, for embeddings I am using jina-ai-v2.

Using a model URL is deprecated, please use the `endpointUrl` parameter instead
Failed to load page within 2s: https://japan.kantei.go.jp/
Failed to load page within 2s: https://japan.kantei.go.jp/101_kishida/meibo/daijin/kishida_e.html
Failed to load page within 2s: https://en.wikipedia.org/wiki/Prime_Minister_of_Japan
Failed to load page within 2s: https://en.wikipedia.org/wiki/Fumio_Kishida
Failed to load page within 2s: https://apnews.com/hub/fumio-kishida
Failed to load page within 2s: https://jp.usembassy.gov/president-biden-welcomes-prime-minister-kishida-to-the-white-house/
Failed to load page within 2s: https://twitter.com/jpn_pmo?lang=en
[14:37:27.633] ERROR (11780): Error scraping webpage: https://japan.kantei.go.jp/
    err: {
      "type": "Error",
      "message": "Failed to load page",
      "stack":
          Error: Failed to load page
              at eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:37:13)
              at Module.withPage (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:61:18)
              at runNextTicks (node:internal/process/task_queues:60:5)
              at process.processImmediate (node:internal/timers:447:9)
              at process.callbackTrampoline (node:internal/async_hooks:130:17)
              at async eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:21:18)
    }
[14:37:27.637] ERROR (11780): Error scraping webpage: https://japan.kantei.go.jp/101_kishida/meibo/daijin/kishida_e.html
    err: {
      "type": "Error",
      "message": "Failed to load page",
      "stack":
          Error: Failed to load page
              at eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:37:13)
              at Module.withPage (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:61:18)
              at runNextTicks (node:internal/process/task_queues:60:5)
              at process.processImmediate (node:internal/timers:447:9)
              at process.callbackTrampoline (node:internal/async_hooks:130:17)
              at async eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:21:18)
    }
[14:37:27.691] ERROR (11780): Error scraping webpage: https://en.wikipedia.org/wiki/Prime_Minister_of_Japan
    err: {
      "type": "Error",
      "message": "Failed to load page",
      "stack":
          Error: Failed to load page
              at eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:37:13)
              at Module.withPage (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:61:18)
              at runNextTicks (node:internal/process/task_queues:60:5)
              at process.processImmediate (node:internal/timers:447:9)
              at process.callbackTrampoline (node:internal/async_hooks:130:17)
              at async eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:21:18)
    }
[14:37:27.694] ERROR (11780): Error scraping webpage: https://en.wikipedia.org/wiki/Fumio_Kishida
    err: {
      "type": "Error",
      "message": "Failed to load page",
      "stack":
          Error: Failed to load page
              at eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:37:13)
              at Module.withPage (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:61:18)
              at runNextTicks (node:internal/process/task_queues:60:5)
              at process.processImmediate (node:internal/timers:447:9)
              at process.callbackTrampoline (node:internal/async_hooks:130:17)
              at async eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:21:18)
    }
[14:37:27.698] ERROR (11780): Error scraping webpage: https://apnews.com/hub/fumio-kishida
    err: {
      "type": "Error",
      "message": "Failed to load page",
      "stack":
          Error: Failed to load page
              at eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:37:13)
              at Module.withPage (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:61:18)
              at runNextTicks (node:internal/process/task_queues:60:5)
              at process.processImmediate (node:internal/timers:447:9)
              at process.callbackTrampoline (node:internal/async_hooks:130:17)
              at async eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:21:18)
    }
[14:37:27.701] ERROR (11780): Error scraping webpage: https://jp.usembassy.gov/president-biden-welcomes-prime-minister-kishida-to-the-white-house/
    err: {
      "type": "Error",
      "message": "Failed to load page",
      "stack":
          Error: Failed to load page
              at eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:37:13)
              at Module.withPage (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:61:18)
              at runNextTicks (node:internal/process/task_queues:60:5)
              at process.processImmediate (node:internal/timers:447:9)
              at process.callbackTrampoline (node:internal/async_hooks:130:17)
              at async eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:21:18)
    }
[14:37:27.706] ERROR (11780): Error scraping webpage: https://twitter.com/jpn_pmo?lang=en
    err: {
      "type": "Error",
      "message": "Failed to load page",
      "stack":
          Error: Failed to load page
              at eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:37:13)
              at Module.withPage (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:61:18)
              at runNextTicks (node:internal/process/task_queues:60:5)
              at process.processImmediate (node:internal/timers:447:9)
              at process.callbackTrampoline (node:internal/async_hooks:130:17)
              at async eval (eval at instantiateModule (file:///C:/Users/91953/ML/my_env/Audit.ai/Web%20modules/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56049:28), <anonymous>:21:18)
    }

**Comment by nsarrazin** [comment]
Are you building locally or using the docker image ?

**Comment by Ubermm** [comment]
I am running it locally, docker crashes my system a lot.

**Comment by bpawnzZ** [comment]
> @nsarrazin Hi, just following up, are there any other workarounds I should try? Also how can I use JinaAI's search service (Reader API) instead of serper.dev?

Get your embeddings model right.  Likely that is your problem
