### ISSUE TITLE
Error when evaluating SSR module error after following setup

### ISSUE THREAD

**Issue by ethayu** [huggingface/chat-ui#1321]
Getting the following when running basic setup. llama.cpp backend works as expected, and my .env.local file is as follows:
```
MODELS=`[
  {
    "name": "Local microsoft/Phi-3-mini-4k-instruct-gguf",
    "tokenizer": "microsoft/Phi-3-mini-4k-instruct-gguf",
    "preprompt": "",
    "chatPromptTemplate": "<s>{{preprompt}}{{#each messages}}{{#ifUser}}<|user|>\n{{content}}<|end|>\n<|assistant|>\n{{/ifUser}}{{#ifAssistant}}{{content}}<|end|>\n{{/ifAssistant}}{{/each}}",
    "parameters": {
      "stop": ["<|end|>", "<|endoftext|>", "<|assistant|>"],
      "temperature": 0.7,
      "max_new_tokens": 1024,
      "truncate": 3071
    },
    "endpoints": [{
      "type" : "llamacpp",
      "baseURL": "http://localhost:8080"
    }],
  },
]`
MONGODB_URL=mongodb://localhost:27017
```

Error I get when running npm run dev:
```
12:15:18 PM [vite] Error when evaluating SSR module /src/lib/server/models.ts:
|- ZodError: [
  {
    "code": "too_small",
    "minimum": 1,
    "type": "string",
    "inclusive": true,
    "exact": false,
    "message": "String must contain at least 1 character(s)",
    "path": [
      0,
      "endpoints",
      0,
      "accessToken"
    ]
  }
]
    at get error (file:///Users/etyu/repos/chat-ui/node_modules/zod/lib/index.mjs:538:31)
    at ZodArray.parse (file:///Users/etyu/repos/chat-ui/node_modules/zod/lib/index.mjs:638:22)
    at /Users/etyu/repos/chat-ui/src/lib/server/models.ts:70:40
    at async instantiateModule (file:///Users/etyu/repos/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56052:9)

12:15:18 PM [vite] Error when evaluating SSR module /src/routes/+layout.server.ts: failed to import "/src/lib/server/models.ts"
|- ZodError: [
  {
    "code": "too_small",
    "minimum": 1,
    "type": "string",
    "inclusive": true,
    "exact": false,
    "message": "String must contain at least 1 character(s)",
    "path": [
      0,
      "endpoints",
      0,
      "accessToken"
    ]
  }
]
    at get error (file:///Users/etyu/repos/chat-ui/node_modules/zod/lib/index.mjs:538:31)
    at ZodArray.parse (file:///Users/etyu/repos/chat-ui/node_modules/zod/lib/index.mjs:638:22)
    at /Users/etyu/repos/chat-ui/src/lib/server/models.ts:70:40
    at async instantiateModule (file:///Users/etyu/repos/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56052:9)

[12:15:18.381] ERROR (9710):
    locals: {
      "sessionId": "b8b522296f2f55a8648c8a37a095205bf39ad3c0d1210f4067dcb41a0a2c437a"
    }
    url: "http://localhost:5173/"
    params: {}
    request: {}
    errorId: "77ab872c-d618-44ec-87e1-65c43ba5040f"
    error: {
      "stack":
          ZodError: [
            {
              "code": "too_small",
              "minimum": 1,
              "type": "string",
              "inclusive": true,
              "exact": false,
              "message": "String must contain at least 1 character(s)",
              "path": [
                0,
                "endpoints",
                0,
                "accessToken"
              ]
            }
          ]
              at get error (file:///Users/etyu/repos/chat-ui/node_modules/zod/lib/index.mjs:538:31)
              at ZodArray.parse (file:///Users/etyu/repos/chat-ui/node_modules/zod/lib/index.mjs:638:22)
              at /Users/etyu/repos/chat-ui/src/lib/server/models.ts:70:40
              at async instantiateModule (file:///Users/etyu/repos/chat-ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:56052:9)
      "issues": [
        {
          "code": "too_small",
          "minimum": 1,
          "type": "string",
          "inclusive": true,
          "exact": false,
          "message": "String must contain at least 1 character(s)",
          "path": [
            0,
            "endpoints",
            0,
            "accessToken"
          ]
        }
      ],
      "name": "ZodError"
    }
```

**Comment by ethayu** [comment]
had to put in a dummy HF_TOKEN value in .env.local

**Comment by ethayu** [comment]
had to put in a dummy HF_TOKEN value in .env.local

**Comment by ALonelySheep** [comment]
This should be mentioned in Quickstart.
