### ISSUE TITLE
Currently pulling model from Ollama, please try again later.

### ISSUE THREAD

**Issue by hadifar** [huggingface/chat-ui#1363]
When I run the provided example with ollama it gives the following error:

```
Error: Currently pulling model from Ollama, please try again later.
    at eval (/project-chatui-ollama/chat-ui/src/lib/server/endpoints/ollama/endpointOllama.ts:43:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.generate (/project-chatui-ollama/chat-ui/src/lib/server/textGeneration/generate.ts:8:30)
    at async textGenerationWithoutTitle (/project-chatui-ollama/chat-ui/src/lib/server/textGeneration/index.ts:56:3)
[21:41:45.358] ERROR (60772): Currently pulling model from Ollama, please try again later.
    err: {
      "type": "Error",
      "message": "Currently pulling model from Ollama, please try again later.",
      "stack":
          Error: Currently pulling model from Ollama, please try again later.
              at eval (/project-chatui-ollama/chat-ui/src/lib/server/endpoints/ollama/endpointOllama.ts:43:13)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Module.generateFromDefaultEndpoint (/project-chatui-ollama/chat-ui/src/lib/server/generateFromDefaultEndpoint.ts:11:23)
              at async generateTitle (/project-chatui-ollama/chat-ui/src/lib/server/textGeneration/title.ts:54:10)
              at async Module.generateTitleForConversation (/project-chatui-ollama/chat-ui/src/lib/server/textGeneration/title.ts:17:19)
```

Here is my `.env.local`:

```
MONGODB_URL=mongodb://localhost:27017
HF_TOKEN=MY_TOKEN

MODELS=`[
  {
      "name": "Ollama Llama3",
      "tokenizer" : "philschmid/meta-llama-3-tokenizer",
      "parameters": {
        "temperature": 0.1,
        "top_p": 0.95,
        "repetition_penalty": 1.2,
        "top_k": 50,
      },
      "endpoints": [
        {
         "type": "ollama",
         "url" : "http://127.0.0.1:11434",
         "ollamaName" : "llama3"
        }
      ]
  }
 ]`
```

**Comment by wgcv** [comment]
Try with `"ollamaName" : "llama3:latest"`

**Comment by hadifar** [comment]
@wgcv thanks it fixed the issue.
