### ISSUE TITLE
Chat title descriptions do not update

### ISSUE THREAD

**Issue by cody151** [huggingface/chat-ui#1370]
Koboldcpp running local Llama 3.1 model and Endpoint is OpenAI API 

Something is wrong, at the moment the chat descriptions in the left side panel do not update to reflect the chat contents and seems to be stuck at "New Chat" please see the screenshot.
![3434g3rg3rg32424f2wrgrgvfws](https://github.com/user-attachments/assets/919b4eec-585d-444a-a9e9-170345b1093d)

I did however notice this on the console running the chat-ui

```
[22:07:18.378] ERROR (1799933): Generation failed
    err: {
      "type": "Error",
      "message": "Generation failed",
      "stack":
          Error: Generation failed
              at Module.generateFromDefaultEndpoint (/home/yas/chat-ui/src/lib/server/generateFromDefaultEndpoint.ts:23:9)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async generateTitle (/home/yas/chat-ui/src/lib/server/textGeneration/title.ts:54:10)
              at async Module.generateTitleForConversation (/home/yas/chat-ui/src/lib/server/textGeneration/title.ts:17:19)
    }

```

**Comment by cody151** [comment]
Update: It appears to be an issue with Koboldcpp rather than chat-ui.

**Comment by cody151** [comment]
> TGI with Message API (OpenAI Compatible API) is also experiencing the same issue.

It's an issue with Kobold or your inference engine rather than Chat-UI, closing...

**Comment by juanjuanignacio** [comment]
Im having the same problem using Ollama treated as Open API, have you solved it?
