### ISSUE TITLE
Multi-turn conversation error (Internal Error: Ancestor not found)

### ISSUE THREAD

**Issue by calycekr** [huggingface/chat-ui#1572]
## Bug description

When attempting to engage in a multi-turn conversation, the following error occurs:
```
[20:27:19.848] ERROR (2978106):
    locals: {
      "sessionId": "2ad207f1070b3f4a8110f78e687df39664bdb0217e228dc2ad606b637b47744e"
    }
    url: "http://localhost/conversation/673b2471f2e899344ee851ac"
    params: {
      "id": "673b2471f2e899344ee851ac"
    }
    request: {}
    message: "Internal Error"
    errorId: "60fac007-92a0-4917-8774-be9bba56653a"
    status: 500
    error: {
      "stack":
          Error: Ancestor not found
              at /home/app/chat-ui/src/lib/utils/tree/buildSubtree.ts:22:26
              at Array.map (<anonymous>)
              at Module.buildSubtree (/home/app/chat-ui/src/lib/utils/tree/buildSubtree.ts:20:27)
              at POST (/home/app/chat-ui/src/routes/conversation/[id]/+server.ts:305:23)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Module.render_endpoint (/home/app/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:43:18)
              at async resolve (/home/app/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:446:17)
              at async Object.handle (/home/app/chat-ui/src/hooks.server.ts:284:19)
              at async Module.respond (/home/app/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:20)
              at async file:///home/app/chat-ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
    }
```

## Steps to reproduce

1. Clone Chat-UI and initialize mongo DB.
2. Initiate a multi-turn conversation.
3. Observe the error message displayed.

## Specs

chat-ui-commit: latest

**Comment by nsarrazin** [comment]
I can reproduce using the docker image. Taking a look.

**Comment by nsarrazin** [comment]
Should be fixed with the latest docker image!
