### ISSUE TITLE
MongoParseError: Invalid scheme

### ISSUE THREAD

**Issue by psawa** [huggingface/chat-ui#207]
I tried to run chat-ui on my mac (Intel 2020, MacOS Ventura 13.3.1), and I get the following error: 

```bash
(base) thibo@mac-M:~/Documents/chat-ui$ npm install 

added 339 packages, and audited 340 packages in 39s

72 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(base) thibo@mac:~/Documents/chat-ui$ npm run dev

> chat-ui@0.1.0 dev
> vite dev

(node:3340) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3340) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

Forced re-optimization of dependencies

  VITE v4.3.5  ready in 2136 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
9:25:43 AM [vite] Error when evaluating SSR module /src/lib/server/database.ts:
|- MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)

9:25:43 AM [vite] Error when evaluating SSR module /src/hooks.server.ts: failed to import "/src/lib/server/database.ts"
|- MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)

MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/Users/thibo/Documents/chat-ui/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/thibo/Documents/chat-ui/node_modules/mongodb/lib/mongo_client.js:46:63)
    at eval (/src/lib/server/database.ts:7:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/thibo/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)
```

The error messages show only when I open http://localhost:5173/ on the browser. The webpage shows: 
<img width="963" alt="image" src="https://github.com/huggingface/chat-ui/assets/38402230/4ceeafea-9fce-4d8e-b6ab-e2c624832613">

Thanks!

**Comment by coyotte508** [comment]
You need to follow this section of the README: https://github.com/huggingface/chat-ui#environment
