### ISSUE TITLE
Amazon DocumentDB MongoServerError:  Aggregation stage not supported: '$lookup on multiple join conditions and uncorrelated subquery

### ISSUE THREAD

**Issue by cfregly** [huggingface/chat-ui#268]
```
MongoServerError: Aggregation stage not supported: '$lookup on multiple join conditions and uncorrelated subquery'
    at Connection.onMessage (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.ondata (node:internal/streams/readable:766:22)
    at TLSSocket.emit (node:events:513:28) {
  ok: 0,
  code: 304,
  operationTime: new Timestamp({ t: 1685146597, i: 1 }),
  [Symbol(errorLabels)]: Set(0) {}
```

any thoughts on a quick fix?

**Comment by sharad-fulcrum** [comment]
Hey @cfregly I am running into similar issue. Curious to know if you have workaround that wouldn't make the query excessively slow

**Comment by omidraha** [comment]
Related links:

- https://docs.aws.amazon.com/documentdb/latest/developerguide/release-notes.html#release-notes.04-3-2024
- https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html#functional-differences.with-mongodb
- https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html 
- https://repost.aws/questions/QUz-BMjlTTTIeCNIFBFSaHpQ/aggregation-stage-not-supported-lookup-on-multiple-join-conditions
