### ISSUE TITLE
Conversation export error : `MongoServerError: $lookup with 'pipeline' may not specify 'localField' or 'foreignField'`

### ISSUE THREAD

**Issue by cfregly** [huggingface/chat-ui#269]
MONGODB_URL=mongodb://127.0.0.1:27017/

```Exporting conversations for model OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5
MongoServerError: $lookup with 'pipeline' may not specify 'localField' or 'foreignField'
    at Connection.onMessage (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/home/ubuntu/chat-ui/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28) {
  ok: 0,
  code: 9,
  codeName: 'FailedToParse',
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by cfregly** [comment]
upgraded mongo (6.x) per https://www.mongodb.com/community/forums/t/lookup-with-pipeline-may-not-specify-localfield-or-foreignfield/201793/9
