### ISSUE TITLE
Unable to build with Docker 

### ISSUE THREAD

**Issue by samichaignonmejai** [huggingface/chat-ui#311]
Hey, 
I'm trying to create a docker container with Chat-Ui but i'm facing a wall. 
I cloned this repo in a folder on a server and modified the `.env` file, thinking that it would be easy to deploy a docker container out of it but I could not be more wrong ! 
After trying to build my container with `docker build -t chat-ui .` I went to the same problem as [here](https://github.com/huggingface/chat-ui/issues/301). 

I tried to build the docker container before and after running `npm install` but I went through the exact same problem, which is that it cannot run in the Dockerfile :
```
RUN --mount=type=secret,id=DOTENV_LOCAL,dst=.env.local \ 
  npm run build
```

At first I thought it was an issue with docker not being able to run` npm install` so I added, at the begining of my dockerfile `CMD npm install` and went also throughout the same issue, I'm guessing it has something to do with the dockerfile itself. 

To reproduce my error, here are the steps :

1. `git clone https://github.com/huggingface/chat-ui.git`
2. `cp .env .env.local `
3. modify my .env.local with my variables
4. `docker build -t chat-ui .`

Here is the error I'm getting when I launch the docker build command :

```
docker build -t chat-ui .
[+] Building 4.3s (16/17)                                                       
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 122B                                          0.0s
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 954B                                       0.0s
 => [internal] load metadata for docker.io/library/node:19                 0.6s
 => [internal] load metadata for docker.io/library/node:19-slim            0.6s
 => [builder-production 1/4] FROM docker.io/library/node:19@sha256:92f06f  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 10.45kB                                       0.0s
 => [stage-2 1/5] FROM docker.io/library/node:19-slim@sha256:f58f1fcf5c9f  0.0s
 => CACHED [builder-production 2/4] WORKDIR /app                           0.0s
 => CACHED [builder-production 3/4] COPY --link --chown=1000 package-lock  0.0s
 => CACHED [builder-production 4/4] RUN --mount=type=cache,target=/app/.n  0.0s
 => CACHED [builder 1/3] RUN --mount=type=cache,target=/app/.npm           0.0s
 => CACHED [builder 2/3] COPY --link --chown=1000 . .                      0.0s
 => CACHED [stage-2 2/5] RUN npm install -g pm2                            0.0s
 => CACHED [stage-2 3/5] COPY --from=builder-production /app/node_modules  0.0s
 => CACHED [stage-2 4/5] COPY --link --chown=1000 package.json /app/packa  0.0s
 => ERROR [builder 3/3] RUN --mount=type=secret,id=DOTENV_LOCAL,dst=.env.  3.7s
------                                                                          
 > [builder 3/3] RUN --mount=type=secret,id=DOTENV_LOCAL,dst=.env.local     npm run build:                                                                      
#0 0.622 
#0 0.622 > chat-ui@0.3.0 build
#0 0.622 > vite build
#0 0.622 
#0 0.831 ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
#0 0.831 
#0 0.831     tsconfig.json:2:12:
#0 0.831       2 │   "extends": "./.svelte-kit/tsconfig.json",
#0 0.831         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#0 0.831 
#0 1.551 
#0 1.551 vite v4.3.9 building SSR bundle for production...
#0 1.583 transforming...
#0 3.551 ✓ 165 modules transformed.
#0 3.551 ✓ built in 2.00s
#0 3.551 "PUBLIC_APP_ASSETS" is not exported by "$env/static/public", imported by "src/lib/components/icons/Logo.svelte".
#0 3.551 file: /app/src/lib/components/icons/Logo.svelte:3:10
#0 3.551 1: <script lang="ts">
#0 3.551 2:   import { page } from "$app/stores";
#0 3.551 3:   import { PUBLIC_APP_ASSETS, PUBLIC_APP_NAME, PUBLIC_ORIGIN } from "$env/static/public";
#0 3.551               ^
#0 3.551 4:   import { base } from "$app/paths";
#0 3.553 error during build:
#0 3.553 RollupError: "PUBLIC_APP_ASSETS" is not exported by "$env/static/public", imported by "src/lib/components/icons/Logo.svelte".
#0 3.553     at error (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
#0 3.553     at Module.error (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:13452:16)
#0 3.553     at Module.traceVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:13863:29)
#0 3.553     at ModuleScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:12418:39)
#0 3.553     at ReturnValueScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:6966:38)
#0 3.553     at ChildScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:6966:38)
#0 3.553     at Identifier.bind (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:8116:40)
#0 3.553     at BinaryExpression.bind (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
#0 3.553     at ConditionalExpression.bind (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
#0 3.553     at TemplateLiteral.bind (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:5735:28)
#0 3.608 npm notice 
#0 3.608 npm notice New minor version of npm available! 9.6.3 -> 9.7.1
#0 3.608 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
#0 3.608 npm notice Run `npm install -g npm@9.7.1` to update!
#0 3.608 npm notice 
------
Dockerfile:20
--------------------
  19 |     
  20 | >>> RUN --mount=type=secret,id=DOTENV_LOCAL,dst=.env.local \
  21 | >>>     npm run build
  22 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

**Comment by nembery** [comment]
Hi, this is probably due to a JSON error in your .env.local file. Make sure your MODEL variable contains valid JSON and you should be good to go.
