### ISSUE TITLE
Invalid referer for POST request

### ISSUE THREAD

**Issue by max9076** [huggingface/chat-ui#315]
I set up a simple Docker Compose Stack to play around with HF:
`
version: "3.8"
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
  mongo-express:
    container_name: mongoexpress
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  chat-ui:
    container_name: frontend
    build:
      context: chat-ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
`

HF is at its newest (tag v0.3). I start up the stack via `docker compose up -d --force-recreate` and connect to localhost:3000. There, I am greeted with the usual ethics modal ("This application is for demonstration purposes only. [...]". When clicking on "Start chatting", I encounter a blank page with the text "Invalid referer for POST request".

Some more information (of the POST request when accepting):
Request Payload: ethicsModalAccepted=true&shareConversationsWithModelAuthors=true&ethicsModalAcceptedAt=&activeModel=OpenAssistant%2Foasst-sft-4-pythia-12b-epoch-3.5&searchEnabled=false
Response: Invalid referer for POST request
Status: 403

I could spot these two errors, although I could not figure out when they occur:
`
13:27:19 1|index  | Error: Not found: /favicon.ico
13:27:19 1|index  |     at resolve (file:///app/build/server/index.js:3838:18)
13:27:19 1|index  |     at resolve (file:///app/build/server/index.js:3713:34)
13:27:19 1|index  |     at Object.handle (file:///app/build/server/chunks/hooks.server-a7e0762a.js:67:26)
13:27:19 1|index  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
13:27:19 1|index  |     at async respond (file:///app/build/server/index.js:3711:22)
13:27:19 1|index  |     at async Array.ssr (file:///app/build/handler.js:1207:3)
13:27:22 1|index  | TypeError: node.component is not a function
13:27:22 1|index  |     at file:///app/build/server/index.js:2398:69
13:27:22 1|index  |     at Array.map (<anonymous>)
13:27:22 1|index  |     at render_response (file:///app/build/server/index.js:2398:46)
13:27:22 1|index  |     at render_page (file:///app/build/server/index.js:3228:18)
13:27:22 1|index  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
13:27:22 1|index  |     at async resolve (file:///app/build/server/index.js:3820:22)
13:27:22 1|index  |     at async Object.handle (file:///app/build/server/chunks/hooks.server-a7e0762a.js:67:20)
13:27:22 1|index  |     at async respond (file:///app/build/server/index.js:3711:22)
13:27:22 1|index  |     at async Array.ssr (file:///app/build/handler.js:1207:3)
`

Here is a picture: [https://i.imgur.com/l2CIKLZ.png](url)

**Comment by bodaay** [comment]
another issue related to .env and PUBLIC_ORIGIN

https://github.com/bodaay/HuggingChatAllInOne

**Comment by mambari** [comment]
Add in .env.local PUBLIC_ORIGIN and rebuild your docker img.
PUBLIC_ORIGIN="http://localhost:3000"
