### ISSUE TITLE
how to work in chat-ui with non streaming data?

### ISSUE THREAD

**Issue by swikrit21** [huggingface/chat-ui#336]
I was working in a chat-ui by providing my endpoints only which is hosted in a localhost:8000/generate. I dont have any model but endpoints only so can you provide me a solution for working in only endpoints and non streaming data( application/json or application/plain). I have model hosted in this server.

in modelEndpoint.ts
if (!model.endpoints) {
		return {
			url: `http://10.0.2.27:8000/generate`,
			// authorization: `Bearer ${HF_ACCESS_TOKEN}`,
			// weight: 1,
		};
	}
in 

Error: An error occurred while fetching the blob
    at request (file:///home/fm-pc-lt-215/Desktop/chat-ui/chat-ui/node_modules/@huggingface/inference/dist/index.mjs:89:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Proxy.textGeneration (file:///home/fm-pc-lt-215/Desktop/chat-ui/chat-ui/node_modules/@huggingface/inference/dist/index.mjs:457:15)
    at async Module.generateFromDefaultEndpoint (/src/lib/server/generateFromDefaultEndpoint.ts:22:28)
    at async POST (/home/fm-pc-lt-215/Desktop/chat-ui/chat-ui/src/routes/conversation/[id]/summarize/+server.ts:30:26)
    at async Module.render_endpoint (/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:388:17)
    at async Object.handle (/src/hooks.server.ts:66:20)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20)
    at async file:///home/fm-pc-lt-215/Desktop/chat-ui/chat-ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:506:22

**Comment by nsarrazin** [comment]
Hey! Thanks for the feedback, indeed for now we don't support non-streaming endpoints. I think it would be super nice to have though, so I'll update this issue to use it for that feature request! :smile:

**Comment by sulabh1** [comment]
How can i use generate endpoint in chat-ui then?https://huggingface.github.io/text-generation-inference/

**Comment by nsarrazin** [comment]
You can't yet! That's why I opened the issue to keep track of the work on the feature :smile:

**Comment by swikrit21** [comment]
I have one scenario to discuss. i have streaming hosted in 10.0.2.27:8080/generate_stream. i dont have any model name just and endpoint which take inputs as an payload(body). how to add this endpoint in chat-ui?
