### ISSUE TITLE
Feature Request: Save messages and error message even if text generation endpoint fails

### ISSUE THREAD

**Issue by loganlebanoff** [huggingface/chat-ui#337]
Situation: Text generation endpoint is not running. Then user sends a message.
Current Behavior: UI throws an error and saves conversation to mongodb like this, with an empty message list.
```
{
    _id: ObjectId('64ac1abc2ac09222e24cc984'),
    title: 'Untitled 5',
    messages: [],
    model: 'GPT',
    createdAt: ISODate('2023-07-10T14:50:36.324Z'),
    updatedAt: ISODate('2023-07-10T14:50:36.324Z'),
    sessionId: '0048fb5c-a224-49c2-a7be-ea417defa6e2'
}
```

Desired behavior: UI throws an error and saves conversation to mongodb with the user's message and the error message inside.
```
{
    _id: ObjectId('64ac1abc2ac09222e24cc984'),
    title: 'Untitled 5',
    messages: [
        {
            content: 'What is 2-2?',
            from: 'user',
            id: '874cfd40-2c61-49fe-b9f6-8b296a79ab6a',
        },
        {
            from: 'assistant',
            error: 'TypeError: fetch failed
    at fetch (C:\chat-ui\node_modules\undici\index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10)
    at async POST (/src/routes/conversation/[id]/+server.ts:90:16)
    at async Module.render_endpoint (/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:388:17)
    at async Object.handle (/src/hooks.server.ts:66:20)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20)
    at async file:///C:/chat-ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:506:22 {
  cause: Error: connect ECONNREFUSED 127.0.0.1:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1532:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 80
  }
}
        },
    ],
    model: 'GPT',
    createdAt: ISODate('2023-07-10T14:50:36.324Z'),
    updatedAt: ISODate('2023-07-10T14:50:36.324Z'),
    sessionId: '0048fb5c-a224-49c2-a7be-ea417defa6e2'
}
```

**Comment by nsarrazin** [comment]
Hey! Thanks for reporting this, indeed the behaviour would make more sense the way you describe it. If someone wants to tackle this feel free or else I'll try at some point.
