### ISSUE TITLE
Searxng as search provider [free, open source]

### ISSUE THREAD

**Issue by flozi00** [huggingface/chat-ui#338]
https://github.com/searxng/searxng
https://searx.space/

Searx would be an free alternative for personal use to the serp providers.
What do you think about integrating it ?
I could start an PR for that if you are open for

**Comment by nsarrazin** [comment]
Hey! I think it would be nice to support an open source search tool for sure. Feel free to open a PR with an integration and let me know if you need help.

**Comment by flozi00** [comment]
Great, I will add it tomorrow

It's only one file, correct ? https://github.com/huggingface/chat-ui/blob/main/src/lib/server/websearch/searchWeb.ts

**Comment by nsarrazin** [comment]
Thanks! Yes it's this file, you can also add an empty entry to the `.env` so people know it's a field that can be filled.

**Comment by RachelShalom** [comment]
Hey after adding the serper api key I'm trying to run the app locally "nmp run dev" and I get an issue related to websearch:

[vite]: Rollup failed to resolve import "@xenova/transformers" from "C:/Users/username/chat-ui/src/lib/server/websearch/sentenceSimilarity.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@xenova/transformers" from "C:/Users/username/chat-ui/src/lib/server/websearch/sentenceSimilarity.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Users/username/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:48142:27)   
    at onRollupWarning (file:///C:/Users/username/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:48174:9)
    at onwarn (file:///C:/Users/username/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:47902:13)     
    at file:///C:/Users/username/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:24152:13
    at Object.logger [as onLog] (file:///C:/Users/username/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:25825:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/rachel_shalom/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:24738:26)
    at file:///C:/Usersusername/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:24698:26
    
how do I externelize this module and should I? anyone had this issue?

**Comment by gary149** [comment]
Feel free to open a PR for it (adding it to the 2 existing providers).
