### ISSUE TITLE
SSL Wrong version number error

### ISSUE THREAD

**Issue by swikrit21** [huggingface/chat-ui#341]
i have added   this
"endpoints": [
        {"url": "http://127.0.0.1:8080/generate_stream", "weight": 100}
    ],

in the model but i am getting this error

TypeError: fetch failed
    at fetch (/home/fm-pc-lt-215/Desktop/chat-ui/chat-ui/node_modules/undici/index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10)
    at async POST (/home/fm-pc-lt-215/Desktop/chat-ui/chat-ui/src/routes/conversation/[id]/+server.ts:91:16)
    at async Module.render_endpoint (/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:388:17)
    at async Object.handle (/src/hooks.server.ts:66:20)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:259:20)
    at async file:///home/fm-pc-lt-215/Desktop/chat-ui/chat-ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:506:22 {
  cause: [Error: C0770BE8547F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
Error: aborted
    at connResetException (node:internal/errors:717:14)
    at abortIncoming (node:_http_server:754:17)
    at socketOnClose (node:_http_server:748:3)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:322:12) {
  code: 'ECONNRESET'
}

**Comment by nsarrazin** [comment]
Where are you hosting chat-ui? Is it on your own machine or a remote server ? :eyes:

**Comment by swikrit21** [comment]
its in my own machines
using localhost

**Comment by davidna22** [comment]
You're probably accidentally setting the endpoint parameter to https rather than http.

**Comment by bilal-rachik** [comment]
I have the same problem. Did you find a solution?
