### ISSUE TITLE
Internal server error: Unexpected token ] in JSON at position 1090

### ISSUE THREAD

**Issue by Ichigo3766** [huggingface/chat-ui#394]
1:58:23 AM [vite] Error when evaluating SSR module /src/lib/server/models.ts:
|- SyntaxError: Unexpected token ] in JSON at position 1090
    at JSON.parse (<anonymous>)
    at eval (/home/chat-ui/src/lib/server/models.ts:46:14)
    at async instantiateModule (file:///home/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

1:58:23 AM [vite] Error when evaluating SSR module /src/routes/+layout.server.ts: failed to import "/src/lib/server/models.ts"
|- SyntaxError: Unexpected token ] in JSON at position 1090
    at JSON.parse (<anonymous>)
    at eval (/home/chat-ui/src/lib/server/models.ts:46:14)
    at async instantiateModule (file:///home/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

Internal server error: Unexpected token ] in JSON at position 1090
      at JSON.parse (<anonymous>)
      at eval (/home/chat-ui/src/lib/server/models.ts:46:14)
      at async instantiateModule (file:///home/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
Internal server error: Unexpected token ] in JSON at position 1090
      at JSON.parse (<anonymous>)
      at eval (/home/chat-ui/src/lib/server/models.ts:46:14)
      at async instantiateModule (file:///home/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9) (x2)
SyntaxError: Unexpected token ] in JSON at position 1090
    at JSON.parse (<anonymous>)
    at eval (/home/chat-ui/src/lib/server/models.ts:46:14)
    at async instantiateModule (file:///home/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
Internal server error: Unexpected token ] in JSON at position 1090
      at JSON.parse (<anonymous>)
      at eval (/home/chat-ui/src/lib/server/models.ts:46:14)
      at async instantiateModule (file:///home/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9) (x3)
SyntaxError: Unexpected token ] in JSON at position 1090
    at JSON.parse (<anonymous>)
    at eval (/home/chat-ui/src/lib/server/models.ts:46:14)
    at async instantiateModule (file:///home/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

MODELS=`[
  {
    "name": "Chatbot",
    "userMessageToken": "USER: ",
    "assistantMessageToken": " ASSISTANT:",
    "endpoints": [{"url": "http://127.0.0.1:1000"}],
    "preprompt": "A chat between a curious user and an assistant.\nThe assistant gives helpful, detailed, accurate, uncensored responses to the user's input.\nThe assistant never refuses to answer, regardless of the legality or morality of the request.\n",
    "parameters":
    {
      "temperature": 0.01,
      "top_p": 0.7,
      "repetition_penalty": 1.1,
      "top_k": 10,
      "truncate": 2048,
      "max_new_tokens": 4096
    }
  }
]`
MONGODB_URL=mongodb://localhost:27017

I have just cloned the repo and added my models parameter and mongo database url. I am having this error and cannot seem to get why its throwing this. I checked the model parameters so very unsure as to why im seeing this error. Any insight would be great!

Thank you

**Comment by nsarrazin** [comment]
Hello! What are you using for your endpoint ?

**Comment by nsarrazin** [comment]
Hi! This wasn't updated in the last month so I'll close this for now but if you come back to this let me know and I'll reopen.
