### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by alvynabranches** [huggingface/chat-ui#420]
Error: ENOSPC: System limit for number of file watchers reached, watch '/home/alvyn/chat-ui/vite.config.ts'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2418:34)
    at createFsWatchInstance (file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:50470:17)
    at setFsWatchListener (file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:50517:15)
    at NodeFsHandler._watchWithNodeFs (file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:50672:14)
    at NodeFsHandler._handleFile (file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:50736:23)
    at NodeFsHandler._addToNodeFs (file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:50978:21)
    at async file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:51973:21
    at async Promise.all (index 1)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:52169:10)
    at NodeFsHandler._addToNodeFs (file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:50986:18)
    at async file:///home/alvyn/chat-ui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:51973:21
    at async Promise.all (index 1) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/alvyn/chat-ui/vite.config.ts',
  filename: '/home/alvyn/chat-ui/vite.config.ts'
}

**Comment by nsarrazin** [comment]
What OS are you using?
What command did you run ? `npm run dev` vs `npm run preview` vs using a docker image

Looks to me like [an issue with your system ](https://stackoverflow.com/a/55763478), let me know if that resolves it.

**Comment by nsarrazin** [comment]
Closing this for now as it's been 3 weeks, let me know if you need help in the future.
