### ISSUE TITLE
running the app with websearch fails

### ISSUE THREAD

**Issue by RachelShalom** [huggingface/chat-ui#438]
Hey after adding the serper api key I'm trying to run the app locally "nmp run dev" and I get an issue related to websearch:

```
[vite]: Rollup failed to resolve import "@xenova/transformers" from "C:/Users/username/chat-ui/src/lib/server/websearch/sentenceSimilarity.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@xenova/transformers" from "C:/Users/username/chat-ui/src/lib/server/websearch/sentenceSimilarity.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Users/username/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:48142:27)   
    at onRollupWarning (file:///C:/Users/username/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:48174:9)
    at onwarn (file:///C:/Users/username/chat-ui/node_modules/vite/dist/node/chunks/dep-df561101.js:47902:13)     
    at file:///C:/Users/username/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:24152:13
    at Object.logger [as onLog] (file:///C:/Users/username/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:25825:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/rachel_shalom/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:24738:26)
    at file:///C:/Usersusername/chat-ui/node_modules/rollup/dist/es/shared/node-entry.js:24698:26
    
```
how do I externelize this module and should I? anyone had this issue?

**Comment by nsarrazin** [comment]
Hi! I can't reproduce this issue, are you dependencies up to date with `npm install` ?

**Comment by RachelShalom** [comment]
thanks @nsarrazin indeed it was an issue of dependencies , npm install fixed it
