### ISSUE TITLE
Where to deploy other than HF?

### ISSUE THREAD

**Issue by mhenrichsen** [huggingface/chat-ui#465]
Hey,

I've been trying to deploy the chat-ui somewhere I can use a custom domain (such as vercel and azure). 

Each of them comes with different problems that I have yet to solve.

Vercel issues described [here](https://github.com/huggingface/chat-ui/issues/212).

It does not seem like I can deploy this as a Azure SWA, as it fails when using the azure-swa-adapter for sveltekit with the following error.

```
Using adapter-azure-swa
✘ [ERROR] Top-level await is currently not supported with the "cjs" output format

    .svelte-kit/output/server/chunks/models.js:94:15:
      94 │ const models = await Promise.all(
         ╵                ~~~~~

✘ [ERROR] Top-level await is currently not supported with the "cjs" output format

    .svelte-kit/output/server/entries/endpoints/conversation/_id_/_server.ts.js:199:18:
      199 │ const extractor = await pipeline("feature-extraction", modelId);
          ╵                   ~~~~~

▲ [WARNING] "./xhr-sync-worker.js" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:31:57:
      31 │ ... require.resolve ? require.resolve("./xhr-sync-worker.js") : null;
         ╵                                       ~~~~~~~~~~~~~~~~~~~~~~

error during build:
Error: Build failed with 2 errors:
.svelte-kit/output/server/chunks/models.js:94:15: ERROR: Top-level await is currently not supported with the "cjs" output format
.svelte-kit/output/server/entries/endpoints/conversation/_id_/_server.ts.js:199:18: ERROR: Top-level await is currently not supported with the "cjs" output format
    at failureErrorWithLog (/github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:1575:15)
    at /github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:1033:28
    at /github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:978:67
    at buildResponseToResult (/github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:1031:7)
    at /github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/github/workspace/node_modules/svelte-adapter-azure-swa/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)


---End of Oryx build logs---
Oryx has failed to build the solution.

```

Any suggestions on how I can otherwise deploy this?

**Comment by mhenrichsen** [comment]
Small update.
I've gotten a little closer using docker. It seems to create the chat-ui but all links for creating new conversations are broken.

```
# Use the official Node.js 18 image as a base image
FROM node:18 AS build

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json to utilize cached Docker layers
COPY package*.json ./

# Install npm dependencies (including devDependencies for building the project)
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the SvelteKit app for production
RUN npm run build

# Production stage
FROM node:18 AS production

WORKDIR /usr/src/app

# Copy package.json and package-lock.json for installing production dependencies
COPY --from=build /usr/src/app/package*.json ./

# Install only production dependencies
RUN npm install --production

# Copy the built app from the build container
COPY --from=build /usr/src/app/build ./build

# Expose the port the app runs on (default is 3000 for the Node adapter)
EXPOSE 3000

# Start the Node.js server
CMD ["node", "build"]

```

**Comment by mhenrichsen** [comment]
^above dockerfile is correct and works. It just binds to 0.0.0.0 which was an issue for my mac.

**Comment by Mesfrum** [comment]
@mhenrichsen I am facing the same problem. Did you find a solution?
