### ISSUE TITLE
chat-ui and TGI Connect Timeout Error

### ISSUE THREAD

**Issue by ViokingTung** [huggingface/chat-ui#485]
Hi, I used TGI as a backend for llama2, when I put TGI endpoints in chat-ui, TGI and chat-ui is in same mechine but it cannot connect. would you give me some suggestions? thank you!

TGI work well.
```shell
curl http://127.0.0.1:8081/generate_stream \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
    -H 'Content-Type: application/json'
    
data:{"token":{"id":13,"text":"\n","logprob":-0.45239258,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":13,"text":"\n","logprob":-0.5541992,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":2772,"text":"De","logprob":-0.016738892,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":1022,"text":"ep","logprob":-0.000002503395,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":6509,"text":" learning","logprob":-0.026168823,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":30081,"text":" ","logprob":-0.08898926,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":29898,"text":"(","logprob":-0.0023441315,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":15189,"text":"also","logprob":-0.0006175041,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":2998,"text":" known","logprob":-0.000029087067,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":408,"text":" as","logprob":-7.1525574e-7,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":30081,"text":" ","logprob":-0.0052261353,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":24535,"text":"deep","logprob":-0.0019664764,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":2281,"text":" struct","logprob":-0.0007429123,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":2955,"text":"ured","logprob":-0.000027537346,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":6509,"text":" learning","logprob":-0.000081300735,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":29897,"text":")","logprob":-0.00006067753,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":338,"text":" is","logprob":-0.00009846687,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":760,"text":" part","logprob":-0.000022292137,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":310,"text":" of","logprob":-3.5762787e-7,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":263,"text":" a","logprob":-0.00013446808,"special":false},"generated_text":"\n\nDeep learning (also known as deep structured learning) is part of a","details":null}    
```

chat-ui **.env.local**  MODELS config:

```shell
MODELS=`[
{
        "name": "Trelis/Llama-2-7b-chat-hf-function-calling",
        "datasetName": "Trelis/function_calling_extended",
        "description": "function calling Llama-7B-chat",
        "websiteUrl": "https://research.Trelis.com",
        "userMessageToken": "",
        "userMessageEndToken": " [/INST] ",
        "assistantMessageToken": "",
        "assistantMessageEndToken": " </s><s>[INST] ",
        "chatPromptTemplate" : "<s>[INST] <<SYS>>\nRespond in French to all questions\n<</SYS>>\n\n{{#each messages}}{{#ifUser}}{{content}} [/INST] {{/ifUser}}{{#ifAssistant}}{{content}} </s><s>[INST] {{/ifAssistant}}{{/each}}",
        "parameters": {
                "temperature": 0.01,
                "top_p": 0.95,
                "repetition_penalty": 1.2,
                "top_k": 50,
                "truncate": 1000,
                "max_new_tokens": 1024
        },
        "endpoints": [{
                "url": "http://127.0.0.1:8081/generate_stream"
        }]
    }
]`   
```

error message:

```shell
[vite] Error when evaluating SSR module /src/lib/server/websearch/sentenceSimilarity.ts:
|- TypeError: fetch failed
    at fetch (/root/chat-ui/node_modules/undici/index.js:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async getModelFile (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
    at async getModelJSON (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
    at async AutoTokenizer.from_pretrained (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
    at async Promise.all (index 0)

2:32:29 PM [vite] Error when evaluating SSR module /src/lib/server/websearch/runWebSearch.ts: failed to import "/src/lib/server/websearch/sentenceSimilarity.ts"
|- TypeError: fetch failed
    at fetch (/root/chat-ui/node_modules/undici/index.js:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async getModelFile (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
    at async getModelJSON (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
    at async AutoTokenizer.from_pretrained (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
    at async Promise.all (index 0)

2:32:29 PM [vite] Error when evaluating SSR module /root/chat-ui/src/routes/conversation/[id]/+server.ts: failed to import "/src/lib/server/websearch/runWebSearch.ts"
|- TypeError: fetch failed
    at fetch (/root/chat-ui/node_modules/undici/index.js:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async getModelFile (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
    at async getModelJSON (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
    at async AutoTokenizer.from_pretrained (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
    at async Promise.all (index 0)

Internal server error: fetch failed
      at fetch (/root/chat-ui/node_modules/undici/index.js:109:13)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at process.processImmediate (node:internal/timers:447:9)
      at async getModelFile (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
      at async getModelJSON (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
      at async Promise.all (index 0)
      at async loadTokenizer (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
      at async AutoTokenizer.from_pretrained (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
      at async Promise.all (index 0)
TypeError: fetch failed
    at fetch (/root/chat-ui/node_modules/undici/index.js:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async getModelFile (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
    at async getModelJSON (file:///root/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
    at async AutoTokenizer.from_pretrained (file:///root/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
    at async Promise.all (index 0) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/root/chat-ui/node_modules/undici/lib/core/connect.js:182:24)
      at /root/chat-ui/node_modules/undici/lib/core/connect.js:129:46
      at Immediate._onImmediate (/root/chat-ui/node_modules/undici/lib/core/connect.js:170:9)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

**Comment by nsarrazin** [comment]
Hi! Can you try without the `/generate_stream` in your .env.local ?

**Comment by ViokingTung** [comment]
> Hi! Can you try without the `/generate_stream` in your .env.local ?

yes, I have already tried without **/generate_stream**, it still not work, and the error message is "**cause: Error: read ECONNRESET**"

**Comment by ViokingTung** [comment]
> Alright, not sure if that could help, but can you try with `https` instead of `http`?

**code: 'UND_ERR_CONNECT_TIMEOUT'**, I am sorry it still not work.

**Comment by ViokingTung** [comment]
I found the answer, just because I can`t visit huggingface.co for special reason. it is not about TGI and chat-ui, sorry for this issue ,I closed it.

**Comment by perfectar** [comment]
> I found the answer, just because I can`t visit huggingface.co for special reason. it is not about TGI and chat-ui, sorry for this issue ,I closed it.

How do you fix this problem？Just change another network environment？

**Comment by Starlento** [comment]
> > I found the answer, just because I can`t visit huggingface.co for special reason. it is not about TGI and chat-ui, sorry for this issue ,I closed it.
> 
> How do you fix this problem？Just change another network environment？

Are you using v0.6? It seems that websearch is a new feature in 0.6. And it is by default using it so that the guide provided by others will not work now. I got the error `[vite] Error when evaluating SSR module /src/lib/server/websearch/sentenceSimilarity.ts:`. So, I just switch to v0.5 and at least it is running...
Maybe v0.6 is new and the document and .env is lagging.

**Comment by ViokingTung** [comment]
> > I found the answer, just because I can`t visit huggingface.co for special reason. it is not about TGI and chat-ui, sorry for this issue ,I closed it.
> 
> How do you fix this problem？Just change another network environment？

yes, for my situation it need to download **'xenova/transformers'** model  from huggingface.co ,so I must confirm I can visit this website.

**Comment by mehdiebrami** [comment]
i use docekr chatui with mongodb

> hello, I got same this error:
> 
> "fetch failed: Connect Timeout Error (attempted address: api-inference.huggingface.co:443"
> 
> Could you please guide me too? Thanks
