### ISSUE TITLE
ChatUI on HuggingFace Spaces errors out with PermissionError: [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by Skrelan** [huggingface/chat-ui#511]
When I try following the below two tutorials I hit the same error, where the container code tries to create a directory and fails due to permission issues on the host

tutorials: 
1. https://huggingface.co/docs/hub/spaces-sdks-docker-chatui#chatui-on-spaces
2. https://huggingface.co/blog/Llama2-for-non-engineers

Note: I have set the env vars `HUGGING_FACE_HUB_TOKEN` and in a prior attempt `HF_TOKEN` as well.

<img width="1252" alt="Screenshot 2023-10-16 at 1 25 04 AM" src="https://github.com/huggingface/chat-ui/assets/9070365/6a54c653-ed30-4bcf-af83-80dc04ce2bc1">

stack trace on hugging face space
```
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 131, in download_weights
    utils.download_and_unload_peft(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/peft.py", line 38, in download_and_unload_peft
    os.makedirs(model_id, exist_ok=True)

  File "/opt/conda/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)

  File "/opt/conda/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: 'skrelan'
```

**Comment by mattnull** [comment]
I am also having this issue

**Comment by jaasperhelin** [comment]
I have the same issue. Added HUGGING_FACE_HUB_TOKEN and HF_TOKEN as secrets in my Space settings. Both tokens are READ. I built the Space anew (Factory rebuild) but still get the same error message as shown above (Errno 13).

![grafik](https://github.com/huggingface/chat-ui/assets/151134635/33c57c82-d2ec-49dc-b6e7-7d1931411af6)

Any solutions yet for this issue?

**Comment by AalianKhan** [comment]
I am having the same issue. Did you guys find any solutions?
