### ISSUE TITLE
Websearch error in proxy

### ISSUE THREAD

**Issue by calycekr** [huggingface/chat-ui#528]
I'm developing in a proxy environment, I'm guessing it's because **websearch module can't import the model(Xenova/gte-small) from huggingface.**
I don't want to use websearch, but it tries to load the gte-small model anyway, and I get an error.

```
11:36:36 AM [vite] Error when evaluating SSR module /src/lib/server/websearch/sentenceSimilarity.ts:
|- TypeError: fetch failed
    at fetch (/home/dev/chat-ui/node_modules/undici/index.js:110:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getModelFile (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
    at async getModelJSON (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 1)
    at async loadTokenizer (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
    at async AutoTokenizer.from_pretrained (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
    at async Promise.all (index 0)
    at async loadItems (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/pipelines.js:2110:5)
    at async Proxy.pipeline (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/pipelines.js:2056:19)

11:36:36 AM [vite] Error when evaluating SSR module /src/lib/server/websearch/runWebSearch.ts: failed to import "/src/lib/server/websearch/sentenceSimilarity.ts"
|- TypeError: fetch failed
    at fetch (/home/dev/chat-ui/node_modules/undici/index.js:110:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getModelFile (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
    at async getModelJSON (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 1)
    at async loadTokenizer (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
    at async AutoTokenizer.from_pretrained (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
    at async Promise.all (index 0)
    at async loadItems (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/pipelines.js:2110:5)
    at async Proxy.pipeline (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/pipelines.js:2056:19)

11:36:36 AM [vite] Error when evaluating SSR module /home/dev/chat-ui/src/routes/conversation/[id]/+server.ts: failed to import "/src/lib/server/websearch/runWebSearch.ts"
|- TypeError: fetch failed
    at fetch (/home/dev/chat-ui/node_modules/undici/index.js:110:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getModelFile (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:468:24)
    at async getModelJSON (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 1)
    at async loadTokenizer (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:56:16)
    at async AutoTokenizer.from_pretrained (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/tokenizers.js:3778:48)
    at async Promise.all (index 0)
    at async loadItems (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/pipelines.js:2110:5)
    at async Proxy.pipeline (file:///home/dev/chat-ui/node_modules/@xenova/transformers/src/pipelines.js:2056:19)

```

1. Is there a workaround to downloading the model directly?
2. Need Improve: the proxy related code.
3. Need Improve: add option to turn off websearch initialization. (

**Comment by nsarrazin** [comment]
Not sure why you can't download it (maybe @xenova has a clue) but we should move the init code to only be called if the websearch is defined for sure. will look into it

**Comment by xenova** [comment]
@calycekr Can you share some more details about your environment? (e.g., OS, node version, vite version, etc.). Also, if possible, could you rerun it with a more-verbose logging level (perhaps for http, so we can see which request it is failing on)?

> 11:36:36 AM [vite] Error when evaluating SSR module /src/lib/server/websearch/sentenceSimilarity.ts:
> |- TypeError: fetch failed

@nsarrazin Perhaps one way we can easily fix this is with lazy-loading (I think this will benefit most users anyway). In this case, we wait to load the pipeline until a web search request is made. The biggest disadvantage with this, of course, is that the first load will be slower:
- If the model is not found locally, it must be downloaded. Subsequent requests (and runs) will use this cached model
- The pipeline construction time (i.e., first run) will also take a short amount of time when the first request is made.

**Comment by michaelfeil** [comment]
Same issue. WebSearch is even disabled in my case.

**Comment by nsarrazin** [comment]
Ok then I think we should do the lazy loading thing, shouldn't be too hard. Will do it later unless someone else wants to give it a shot first!

**Comment by nsarrazin** [comment]
We merged a fix for this, can you give this another go ? @calycekr @michaelfeil
