### ISSUE TITLE
How can I use this offline with local models?

### ISSUE THREAD

**Issue by iChristGit** [huggingface/chat-ui#549]
I really like the web_search feature, can I somehow use it with local models? I tried but I dont see any bat files to launch it.

**Comment by gary149** [comment]
A guide for local models / local use is coming soon!

**Comment by iChristGit** [comment]
> A guide for local models / local use is coming soon!

Another quick question, does web search will always rely on api? cant it be done locally using chrome ? or using duckduckgo api ?

**Comment by nsarrazin** [comment]
Currently the web search relies on an API but if someone wants to add support for something that could run directly in the server we would gladly merge it! 

And I'm writing a guide on how to run the app with llama.cpp for example 😁 Will ping you when it's out!

**Comment by iChristGit** [comment]
> Currently the web search relies on an API but if someone wants to add support for something that could run directly in the server we would gladly merge it!
> 
> And I'm writing a guide on how to run the app with llama.cpp for example 😁 Will ping you when it's out!

Thanks for the informaion,
sadly im not good at coding or understanding the under the hood stuff,
but I have been using this extension (https://github.com/simbake/web_search)
It takes like 5 second to gather the information directly from chrome on my machine, not relying on api or other services.
There is also LolLLMs which implemented a great search agent, which takes around 30-60 second but gives his sources and can go through tens of pages to gather information.

Hopefully in a couple of months Chat-UI will be the perfect solution for accurate LLMS!

**Comment by nsarrazin** [comment]
Support for llama.cpp and openAI compatible endpoints (text generaiton webui, vllm, etc.) has been merged into main! 

Regarding the fully local websearch I think this is a fairly low hanging fruit, I opened [this issue](https://github.com/huggingface/chat-ui/issues/553) to track it specifically.

**Comment by iChristGit** [comment]
> Support for llama.cpp and openAI compatible endpoints (text generaiton webui, vllm, etc.) has been merged into main!
> 
> Regarding the fully local websearch I think this is a fairly low hanging fruit, I opened [this issue](https://github.com/huggingface/chat-ui/issues/553) to track it specifically.

Thank you for the update, we can close the issue now, just before that how can I connect chat-ui and oobabooga? I have it set with the --api on latest version (openai compatible api)

**Comment by iChristGit** [comment]
> Support for llama.cpp and openAI compatible endpoints (text generaiton webui, vllm, etc.) has been merged into main!
> 
> Regarding the fully local websearch I think this is a fairly low hanging fruit, I opened [this issue](https://github.com/huggingface/chat-ui/issues/553) to track it specifically.

Hey, I am trying to run it locally with no success,  I have mango DB but getting an error when trying to genereate anything (with use of oogabooga webui)


  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
APIConnectionError: Connection error.
    at OpenAI.makeRequest (file:///C:/ChatUI/node_modules/openai/core.mjs:269:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (C:/ChatUI/src/lib/server/endpoints/openai/endpointOai.ts:65:9)
    at async Module.generateFromDefaultEndpoint (C:/ChatUI/src/lib/server/generateFromDefaultEndpoint.ts:10:23)
    at async Module.summarize (C:/ChatUI/src/lib/server/summarize.ts:28:10)
    at async Object.start (C:/ChatUI/src/routes/conversation/[id]/+server.ts:160:24) {
  status: undefined,
  headers: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: FetchError: request to http://localhost:5000/chat/completions failed, reason: connect ECONNREFUSED ::1:5000
      at ClientRequest.<anonymous> (C:\ChatUI\node_modules\node-fetch\lib\index.js:1501:11)
      at ClientRequest.emit (node:events:517:28)
      at Socket.socketErrorListener (node:_http_client:501:9)
      at Socket.emit (node:events:529:35)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED'
  }
}
APIConnectionError: Connection error.
    at OpenAI.makeRequest (file:///C:/ChatUI/node_modules/openai/core.mjs:269:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (C:/ChatUI/src/lib/server/endpoints/openai/endpointOai.ts:65:9)
    at async Object.start (C:/ChatUI/src/routes/conversation/[id]/+server.ts:186:36) {
  status: undefined,
  headers: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: FetchError: request to http://localhost:5000/chat/completions failed, reason: connect ECONNREFUSED ::1:5000
      at ClientRequest.<anonymous> (C:\ChatUI\node_modules\node-fetch\lib\index.js:1501:11)
      at ClientRequest.emit (node:events:517:28)
      at Socket.socketErrorListener (node:_http_client:501:9)
      at Socket.emit (node:events:529:35)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED'
  }
  

I hvae tried with /v1/ and with with different ports, and this is the port used
What Am i doing wrong?

**Comment by nsarrazin** [comment]
Try replacing localhost with 127.0.0.1 ?

**Comment by iChristGit** [comment]
I feel very stupid! now it works
Il try to do the local searching now! thank you so much for the hard work
