### ISSUE TITLE
Generation failed (Module.summarize) when using TogetherAI openai compatible endpoint

### ISSUE THREAD

**Issue by gururise** [huggingface/chat-ui#655]
TogetherAI offers an [OpenAI compatible endpoint](https://docs.together.ai/docs/openai-api-compatibility).  When using this endpoint with the model setup as follows:

```
MODELS=`[
    {
      "name": "mistralai/Mixtral-8x7b-Instruct-v0.1",
      "displayName": "Mixtral-8x7b",
      "endpoints" : [{
        "type": "openai",
        "baseURL": "https://api.together.xyz/v1"
      }],
      "promptExamples": [
        {
          "title": "Write an email from bullet list",
          "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
        }, {
          "title": "Code a snake game",
          "prompt": "Code a basic snake game in python, give explanations for each step."
        }, {
          "title": "Assist in a task",
          "prompt": "How do I make a delicious lemon cheesecake?"
        }
      ]
    }
]`
```

Inference and streaming work just fine with the output displayed in the chat window; however, in the console, the following error always appears after every interaction:
```
Error: Generation failed
    at Module.generateFromDefaultEndpoint (/home/gene/Downloads/chat-ui/src/lib/server/generateFromDefaultEndpoint.ts:22:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.summarize (/home/gene/Downloads/chat-ui/src/lib/server/summarize.ts:28:10)
    at async eval (/home/gene/Downloads/chat-ui/src/routes/conversation/[id]/+server.ts:167:26)
```

**Comment by gururise** [comment]
Ok, seems like the TASK_MODEL does not respect the "endpoints" config.  If I use w/o endpoints, it will hit the huggingface inference endpoint and now summarization works.

**Comment by trickster** [comment]
I have the same problem @gururise , do you have any solution?
