### ISSUE TITLE
SyntaxError: JSON5: invalid character 'm' at 1:1

### ISSUE THREAD

**Issue by mhenrichsen** [huggingface/chat-ui#851]
Hello,

When I change my model name from: 
```
{
    "name" : "mhenrichsen/danskgpt-chat-v2",
    "description" : "DanskGPT v2.1 er den bedste af DanskGPT modellerne. Modellen kan prøves gratis her på siden.",
    "websiteUrl" : "https://danskgpt.dk",
    "parameters": {
      "temperature": 0.9,
      "top_p": 0.95,
      "repetition_penalty": 1.2,
      "top_k": 50,
      "truncate": 2048,
      "max_new_tokens": 4096,
      "stop": []
    },
    "endpoints": [{
      "type" : "openai",
      "baseURL": "http://34.91.100.254:8888/v1"
    }],
    "promptExamples" : [
      {
        "title": "Hvem har lavet dig?",
        "prompt": "Hvem har lavet dig?"
      }, {
        "title": "Hvornår vandt Danmark EM?",
        "prompt": "Hvornår vandt Danmark EM i fodbold?"
      },
    ]
  },
```
to
```
{
    "name" : "mhenrichsen/danskgpt-chat-v21",
 ....
 ```
 I get the following error.
 ```
 SyntaxError: JSON5: invalid character 'm' at 1:1
    at syntaxError (/Users/mads/Desktop/chat-ui-hf/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/Users/mads/Desktop/chat-ui-hf/node_modules/json5/lib/parse.js:1055:12)
    at Object.value (/Users/mads/Desktop/chat-ui-hf/node_modules/json5/lib/parse.js:309:15)
    at lex (/Users/mads/Desktop/chat-ui-hf/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/Users/mads/Desktop/chat-ui-hf/node_modules/json5/lib/parse.js:25:17)
    at /Users/mads/Desktop/chat-ui-hf/src/lib/server/models.ts:158:48
    at async instantiateModule (file:///Users/mads/Desktop/chat-ui-hf/node_modules/vite/dist/node/chunks/dep-52909643.js:56052:9) {
  lineNumber: 1,
  columnNumber: 1
}
```

Any ideas? Seems super strange that changing model name causes this issue.

**Comment by rodrigobdz** [comment]
@mhenrichsen I'm facing a similar issue (see below), could you elaborate on what was the issue in your case and how you solved it?
