### ISSUE TITLE
what is the difference between "chat-ui-db" docker image and "chat-ui" docker image?

### ISSUE THREAD

**Issue by majestichou** [huggingface/chat-ui#852]
I found there are 2 packages in the chat-ui repository: one is chat-ui and the other is chat-ui-db. what is the difference between "chat-ui-db" docker image and "chat-ui" docker image?

I've pulled two images from the mirror site: huggingface/text-generation-inference:1.4 and mongo:latest. 

I hope to use the two images( huggingface/text-generation-inference:1.4 and mongo:latest.) and the image of chat-ui or chat-ui-db to implement the local large model Q&A service. What should I do? Should I use "chat-ui-db" docker image or Should I use "chat-ui" docker image.

What should i do to complete my task of local large model Q&A service? Can anyone give detailed help?

**Comment by nsarrazin** [comment]
So `chat-ui-db` comes with mongo built-in, useful for quick testing and local deployments. `chat-ui` doesn't have a DB included, so you will need to specify your `MONGODB_URL`. in your env config. Will update the docs to reflect this!

**Comment by majestichou** [comment]
> So `chat-ui-db` comes with mongo built-in, useful for quick testing and local deployments. `chat-ui` doesn't have a DB included, so you will need to specify your `MONGODB_URL`. in your env config. Will update the docs to reflect this!

I tried` chat-ui-db` and everything works fine. But I used the `chat-ui` image and it failed to boot. The reproduction process is as follows:
`docker run --rm -it huggingface/chat-ui:latest`
The error information is:

```
DOTENV_LOCAL was not found in the ENV variables and .env.local is not set using a bind volume. We are using the default .env config.

> chat-ui@0.7.0 build
> vite build

▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


vite v4.5.2 building SSR bundle for production...
"BaseClient" and "TokenSet" are imported from external module "openid-client" but never used in "src/lib/server/auth.ts".
✓ 271 modules transformed.

node:internal/event_target:1100
  process.nextTick(() => { throw err; });
                           ^
Error: Please specify the MONGODB_URL environment variable inside .env.local. Set it to mongodb://localhost:27017 if you are running MongoDB locally, or to a MongoDB Atlas free instance for example.
    at file:///app/.svelte-kit/output/server/chunks/database.js:4:9
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async analyse (file:///app/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:60:16)
    at async MessagePort.<anonymous> (file:///app/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.11.1

> chat-ui@0.7.0 preview
> vite preview --host 0.0.0.0 --port 3000


error when starting preview server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/.svelte-kit/output/server/manifest.js' imported from /app/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:158:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at preview (file:///app/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:47:75)
```
