### ISSUE TITLE
crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by ihubanov** [huggingface/chat-ui#868]
In getting this error in browser console:
```
TypeError: crypto.randomUUID is not a function
    addChildren addChildren.ts:25
    writeMessage +page.svelte:155
+page.svelte:320:11
```
Anyone having the same issue?

**Comment by ihubanov** [comment]
Looks like this only happens when loading the chat-ui from the network... When on localhost it works fine... Also tried different browsers it has the same issue in all... Something wrong with vite?

**Comment by pcnudde** [comment]
I get this as well. I'm seeing strange behaviour when running on the network while localhost is fine. This one I only saw using 'npm run dev' I have not seen this one running pm2, but I'm seeing strange 405s as soon as I don't run localhost.

**Comment by pcnudde** [comment]
Could it be that the function is only available in secure contexts (https and localhost) ?

**Comment by pcnudde** [comment]
Confirmed that the secure context is the issue. It will work on localhost, on https, but not over http. If you use chrome you can make it work by enabling 'Insecure origins treated as secure' on the url to prove the point.

**Comment by ihubanov** [comment]
> Confirmed that the secure context is the issue. It will work on localhost, on https, but not over http. If you use chrome you can make it work by enabling 'Insecure origins treated as secure' on the url to prove the point. 
> 

I'll give it a try, thanks!

**Comment by seongminp** [comment]
So is chat-ui ending support for non-https non-localhost environments?

**Comment by davideuler** [comment]
I've a history revision, it works for http:
```
git checkout -b fead fead39f
```

**Comment by ihubanov** [comment]
> Confirmed that the secure context is the issue. It will work on localhost, on https, but not over http. If you use chrome you can make it work by enabling 'Insecure origins treated as secure' on the url to prove the point.

Ok now I've setup an nginx to handle the https requests from the user and proxypass to the vite... I'm also handling the websockets. Now I don't have this error and actually get the first response, but it seems like I get it in one pass not streamed like word by word... also if I ask subsequent response... vite crashes with this error:
```Error: Generation failed
    at Module.generateFromDefaultEndpoint (/home/sniffski/Documents/chat-ui/src/lib/server/generateFromDefaultEndpoint.ts:22:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.summarize (/home/sniffski/Documents/chat-ui/src/lib/server/summarize.ts:28:10)
    at async eval (/home/sniffski/Documents/chat-ui/src/routes/conversation/[id]/+server.ts:231:26)
    at async Object.start (/home/sniffski/Documents/chat-ui/src/routes/conversation/[id]/+server.ts:324:7)
Error: Ancestor not found
    at /home/sniffski/Documents/chat-ui/src/lib/utils/tree/buildSubtree.ts:22:26
    at Array.map (<anonymous>)
    at Module.buildSubtree (/home/sniffski/Documents/chat-ui/src/lib/utils/tree/buildSubtree.ts:20:27)
    at POST (/home/sniffski/Documents/chat-ui/src/routes/conversation/[id]/+server.ts:236:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.render_endpoint (/home/sniffski/Documents/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:43:18)
    at async resolve (/home/sniffski/Documents/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:404:17)
    at async Object.handle (/home/sniffski/Documents/chat-ui/src/hooks.server.ts:150:19)
    at async Module.respond (/home/sniffski/Documents/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:20)
    at async file:///home/sniffski/Documents/chat-ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:510:22
````

**Comment by mkguru77** [comment]
The following method automatically adds self signed certificate to system and browsers. With this you can make the app available across local network.

// use linuxbrew if you are linux //
brew install mkcert
brew install nss

// for ubuntu/debian additionally install this
apt install libnss3-tools

// creates root-ca
mkcert -install

// creates cert.pem and key.pem, local domain name is optional or it can be anything
mkcert -key-file ssl/key.pem -cert-file ssl/cert.pem "chatui.local"

// add this to vite.config.ts in defineConfig
import fs from "fs";

server: {
	https: {
		key: fs.readFileSync('path/to/key.pem'),
		cert: fs.readFileSync('path/to/cert.pem')
	},
}

To make app available on other devices in local network, modify "vite dev" to "vite dev --host" in package.json and then "npm run dev".

Crypto: randomUUID() method will only work in https or localhost. Even if we disable this on the server side, clients will still refuse as long as the app uses crypto uuid.
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by nsarrazin** [comment]
Hi I merged some changes to main, can you pull the latest version and tell me if things are working better on your hand ? Feel free to reopen if not!

**Comment by mkguru77** [comment]
> Hi I merged some changes to main, can you pull the latest version and tell me if things are working better on your hand ? Feel free to reopen if not!

Works fine now. I actually tried to do exactly what you just did locally but I'm not very good in coding :confused:

**Comment by julien-c** [comment]
thanks a lot @nsarrazin 🔥

**Comment by ihubanov** [comment]
Now after "git pull" I have the same issue with UUID...

`[MIGRATIONS] All migrations already applied.
10:23:13 AM [vite] Error when evaluating SSR module /home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts: failed to import "uuid"
|- Error: Cannot find module 'uuid' imported from '/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts'
    at nodeImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56088:25)
    at ssrImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:55990:30)
    at eval (/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts:10:37)
    at async instantiateModule (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56052:9)

Error: Cannot find module 'uuid' imported from '/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts'
    at nodeImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56088:25)
    at ssrImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:55990:30)
    at eval (/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts:10:37)
    at async instantiateModule (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56052:9) {
  code: 'ERR_MODULE_NOT_FOUND'
}`

**Comment by ihubanov** [comment]
Now after "git pull" I have the same issue with UUID...

```[MIGRATIONS] All migrations already applied.
10:23:13 AM [vite] Error when evaluating SSR module /home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts: failed to import "uuid"
|- Error: Cannot find module 'uuid' imported from '/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts'
    at nodeImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56088:25)
    at ssrImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:55990:30)
    at eval (/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts:10:37)
    at async instantiateModule (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56052:9)

Error: Cannot find module 'uuid' imported from '/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts'
    at nodeImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56088:25)
    at ssrImport (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:55990:30)
    at eval (/home/<<USER>>/Documents/chat-ui/src/routes/conversation/+server.ts:10:37)
    at async instantiateModule (file:///home/<<USER>>/Documents/chat-ui/node_modules/vite/dist/node/chunks/dep-52909643.js:56052:9) {
  code: 'ERR_MODULE_NOT_FOUND'
}```

**Comment by nsarrazin** [comment]
Maybe obvious but did you run `npm install` after pulling?

**Comment by ihubanov** [comment]
Maybe obvious to smart guys you mean... :rofl: I just did and it works again!

**Comment by instpe** [comment]
> Confirmed that the secure context is the issue. It will work on localhost, on https, but not over http. If you use chrome you can make it work by enabling 'Insecure origins treated as secure' on the url to prove the point.

it works thanks you very much
