### ISSUE TITLE
DeepInfra endpoint errors

### ISSUE THREAD

**Issue by Martok88** [huggingface/chat-ui#922]
Has anyone been able to use DeepInfra endpoints successfully?

If I try using it in a conversation I get this in the error log:
```
TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at new NodeError (node:internal/errors:405:5)
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1045:13)
    at update (file:///home/debian/chat-ui/build/server/chunks/_server.ts-b4356b9c.js:673:20)
    at file:///home/debian/chat-ui/build/server/chunks/_server.ts-b4356b9c.js:683:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.start (file:///home/debian/chat-ui/build/server/chunks/_server.ts-b4356b9c.js:784:7) {
  code: 'ERR_INVALID_STATE'
}
```

If I try using it as a task model, I get this instead:
```
NotFoundError: 404 status code (no body)
    at APIError.generate (file:///home/debian/chat-ui/build/server/chunks/index-8c2ab54f.js:88227:20)
    at OpenAI.makeStatusError (file:///home/debian/chat-ui/build/server/chunks/index-8c2ab54f.js:88999:25)
    at OpenAI.makeRequest (file:///home/debian/chat-ui/build/server/chunks/index-8c2ab54f.js:89038:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async async.messages.messages (file:///home/debian/chat-ui/build/server/chunks/models-d9eaae95.js:213:9)
    at async generateFromDefaultEndpoint (file:///home/debian/chat-ui/build/server/chunks/_server.ts-ff631dba.js:75:23)
    at async summarize (file:///home/debian/chat-ui/build/server/chunks/_server.ts-ff631dba.js:324:10)
    at async file:///home/debian/chat-ui/build/server/chunks/_server.ts-ff631dba.js:682:26
    at async Object.start (file:///home/debian/chat-ui/build/server/chunks/_server.ts-ff631dba.js:784:7) {
  status: 404,
  headers: {
    connection: 'keep-alive',
    'content-length': '22',
    'content-type': 'application/json',
    date: 'Sat, 09 Mar 2024 19:08:59 GMT',
    server: 'uvicorn',
    'x-robots-tag': 'noindex'
  },
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
```

This is my model config:
```
    {
      "name": "mistralai/Mistral-7B-Instruct-v0.1",
      "displayName": "Mistral 7B",
      "description": "A 7B dense Transformer, fast-deployed and easily customisable. Small, yet powerful for a variety of use cases. Supports English and code, and a 8k context window.",
      "parameters": {
        "temperature": 0.5,
        "max_new_tokens": 4096
      },
      "endpoints": [{
        "type": "openai",
        "completion": "completions",
        "baseURL": "https://api.deepinfra.com/v1/openai/completions",
        "apiKey": ""
      }]
    }
```

**Comment by VincentSkylark** [comment]
You are almost there: the `baseURL` should be `https://api.deepinfra.com/v1/openai`:
